### ISSUE TITLE
Recurrence problem

### ISSUE THREAD

**Issue by Pursuerwener** [WangXFng/CaDRec#1]
Thank you very much for sharing your work. I have a question. What is the meaning of the best value in the final output result？

[I 2024-07-26 13:55:59,789] Trial 4 finished with value: 0.20206 and parameters: {}. Best is trial 1 with value: 0.20268.

How do I find the highest reccall@5/ndcg@5,recall@10/ndcg@10,recall@20/ndcg@20 like the results of the experiment in your paper

**Comment by WangXFng** [comment]
Thank you for your attention to our work!
The best trial is for tuning hyperparameters through the Optuna tool. 
If you don't want to tune hyperparameters, just set the n_trials=1 in Line. 260  in Main.py.

**Comment by Pursuerwener** [comment]
So do I need to look for the best test recall and ndcg from all the epochs after the code runs and outputs this result?

Dataset: douban-book #User: 12859 #ITEM 22294
ABLATION:  Full
BETA_1 0.07    
[I 2024-07-26 18:22:17,413] A new study created in memory with name: no-name-b749b3a4-8808-4138-b856-0718f8c086d9
[Info] parameters: Namespace(device=device(type='cuda'), beta=0.9802, lambda_=0.7473, lr=0.01, epoch=30, n_layers=1, batch_size=32, dropout=0.5, smooth=0.03, d_model=512, n_head=1)
Loading  ./data/douban-book/item_matrix.npy ...
Computing adj matrix ...
[Info] Loading data...
[Info] Number of parameters: 18785792
[ Epoch 1 ]
(Training)  P@k:[0.02762, 0.02348, 0.01942, 0.0156],    R@k:[0.00677, 0.02925, 0.0462, 0.0681], 
(Training)map@k:[0.02762, 0.05393, 0.0598, 0.0615], ndcg@k:[0.02762, 0.03145, 0.03616, 0.0434], elapse:0.565 min
(Test)  P@k:[0.10164, 0.07589, 0.06122, 0.04785],    R@k:[0.01314, 0.04681, 0.07177, 0.10775],
(Test)map@k:[0.10164, 0.15979, 0.16334, 0.15605], ndcg@k:[0.10164, 0.08913, 0.08735, 0.09319], elapse:0.306 min
[ Epoch 2 ]
(Training)  P@k:[0.05927, 0.0424, 0.0346, 0.02689],    R@k:[0.01691, 0.0553, 0.08457, 0.12301], 
(Training)map@k:[0.05927, 0.10009, 0.10737, 0.10727], ndcg@k:[0.05927, 0.06096, 0.06889, 0.08094], elapse:0.547 min
(Test)  P@k:[0.14372, 0.09656, 0.07778, 0.06035],    R@k:[0.01908, 0.0591, 0.09137, 0.13508], 
(Test)map@k:[0.14372, 0.20137, 0.20296, 0.19028], ndcg@k:[0.14372, 0.11619, 0.11338, 0.11981], elapse:0.304 min
[ Epoch 3 ]
(Training)  P@k:[0.08356, 0.05518, 0.04392, 0.03338],    R@k:[0.02637, 0.07469, 0.11031, 0.15843], 
(Training)map@k:[0.08356, 0.13119, 0.13754, 0.13642], ndcg@k:[0.08356, 0.08269, 0.0919, 0.10659], elapse:0.546 min
(Test)  P@k:[0.16072, 0.11119, 0.08753, 0.0668],    R@k:[0.02145, 0.06677, 0.10222, 0.14963], 
(Test)map@k:[0.16072, 0.22513, 0.22399, 0.20988], ndcg@k:[0.16072, 0.13278, 0.12813, 0.13415], elapse:0.306 min
[ Epoch 4 ]
(Training)  P@k:[0.09543, 0.06354, 0.04906, 0.03677],    R@k:[0.03063, 0.08568, 0.12345, 0.17391], 
(Training)map@k:[0.09543, 0.14843, 0.15512, 0.15186], ndcg@k:[0.09543, 0.09534, 0.10431, 0.11967], elapse:0.543 min
(Test)  P@k:[0.18673, 0.12439, 0.09692, 0.07262],    R@k:[0.0251, 0.07538, 0.11219, 0.1603], 
(Test)map@k:[0.18673, 0.24853, 0.24591, 0.22973], ndcg@k:[0.18673, 0.14982, 0.14304, 0.1476], elapse:0.305 min
[ Epoch 5 ]
(Training)  P@k:[0.10832, 0.06971, 0.05389, 0.03977],    R@k:[0.03243, 0.09078, 0.13406, 0.18523], 
(Training)map@k:[0.10832, 0.1631, 0.16924, 0.16454], ndcg@k:[0.10832, 0.10352, 0.11331, 0.1285], elapse:0.543 min
(Test)  P@k:[0.1973, 0.13156, 0.10232, 0.07625],    R@k:[0.02678, 0.08006, 0.11796, 0.16749], 
(Test)map@k:[0.1973, 0.26177, 0.25675, 0.23907], ndcg@k:[0.1973, 0.15862, 0.15124, 0.15542], elapse:0.304 min
[ Epoch 6 ]
(Training)  P@k:[0.11291, 0.07458, 0.05787, 0.04289],    R@k:[0.03381, 0.09742, 0.14333, 0.20007], 
(Training)map@k:[0.11291, 0.17182, 0.17714, 0.17073], ndcg@k:[0.11291, 0.10973, 0.12042, 0.13752], elapse:0.545 min
(Test)  P@k:[0.2109, 0.13668, 0.10533, 0.07901],    R@k:[0.02909, 0.08466, 0.12285, 0.17488], 
(Test)map@k:[0.2109, 0.27458, 0.26853, 0.24862], ndcg@k:[0.2109, 0.16648, 0.15789, 0.16286], elapse:0.305 min
[ Epoch 7 ]
(Training)  P@k:[0.12312, 0.07834, 0.0606, 0.04504],    R@k:[0.03702, 0.10228, 0.1501, 0.20732], 
(Training)map@k:[0.12312, 0.18299, 0.18772, 0.18124], ndcg@k:[0.12312, 0.11712, 0.12793, 0.14523], elapse:0.542 min
(Test)  P@k:[0.21568, 0.13964, 0.10845, 0.08186],    R@k:[0.03096, 0.08799, 0.12746, 0.18183], 
(Test)map@k:[0.21568, 0.28102, 0.27557, 0.25419], ndcg@k:[0.21568, 0.17105, 0.16311, 0.16893], elapse:0.304 min
[ Epoch 8 ]
(Training)  P@k:[0.127, 0.08049, 0.06273, 0.04671],    R@k:[0.03841, 0.10556, 0.15448, 0.21529], 
(Training)map@k:[0.127, 0.18775, 0.19226, 0.18441], ndcg@k:[0.127, 0.1201, 0.13155, 0.14988], elapse:0.542 min
(Test)  P@k:[0.22569, 0.14729, 0.11301, 0.08469],    R@k:[0.03182, 0.09249, 0.13249, 0.18716], 
(Test)map@k:[0.22569, 0.29304, 0.28478, 0.26158], ndcg@k:[0.22569, 0.17975, 0.17015, 0.17524], elapse:0.304 min
[ Epoch 9 ]
(Training)  P@k:[0.12771, 0.08376, 0.06446, 0.0485],    R@k:[0.03775, 0.11003, 0.15771, 0.22188], 
(Training)map@k:[0.12771, 0.19248, 0.19653, 0.18844], ndcg@k:[0.12771, 0.12392, 0.13455, 0.15391], elapse:0.541 min
(Test)  P@k:[0.22523, 0.14786, 0.11582, 0.08609],    R@k:[0.03253, 0.0939, 0.13607, 0.19072], 
(Test)map@k:[0.22523, 0.29335, 0.28539, 0.26278], ndcg@k:[0.22523, 0.18056, 0.17296, 0.1778], elapse:0.305 min
[ Epoch 10 ]
(Training)  P@k:[0.13, 0.0855, 0.06643, 0.05038],    R@k:[0.0388, 0.11109, 0.16164, 0.23005], 
(Training)map@k:[0.13, 0.19555, 0.19917, 0.19153], ndcg@k:[0.13, 0.12639, 0.13795, 0.15878], elapse:0.543 min
(Test)  P@k:[0.22882, 0.15117, 0.11691, 0.08669],    R@k:[0.03293, 0.09524, 0.13752, 0.19238], 
(Test)map@k:[0.22882, 0.29741, 0.29021, 0.26707], ndcg@k:[0.22882, 0.18374, 0.17505, 0.17965], elapse:0.305 min
[ Epoch 11 ]
(Training)  P@k:[0.14805, 0.09707, 0.07617, 0.0578],    R@k:[0.04735, 0.13003, 0.18841, 0.26508], 
(Training)map@k:[0.14805, 0.21956, 0.22219, 0.21193], ndcg@k:[0.14805, 0.14659, 0.16042, 0.1835], elapse:0.545 min
(Test)  P@k:[0.23681, 0.15628, 0.12211, 0.09076],    R@k:[0.03456, 0.09836, 0.1436, 0.20073], 
(Test)map@k:[0.23681, 0.30753, 0.29861, 0.27391], ndcg@k:[0.23681, 0.19052, 0.18274, 0.18773], elapse:0.305 min
[ Epoch 12 ]
(Training)  P@k:[0.14994, 0.09907, 0.07782, 0.05899],    R@k:[0.04803, 0.13298, 0.19301, 0.27217], 
(Training)map@k:[0.14994, 0.22286, 0.22574, 0.21562], ndcg@k:[0.14994, 0.149, 0.16341, 0.18721], elapse:0.544 min
(Test)  P@k:[0.24315, 0.15922, 0.12347, 0.09211],    R@k:[0.03531, 0.10087, 0.14532, 0.20453], 
(Test)map@k:[0.24315, 0.31338, 0.30336, 0.27817], ndcg@k:[0.24315, 0.19459, 0.18562, 0.19102], elapse:0.304 min
[ Epoch 13 ]
(Training)  P@k:[0.15042, 0.1007, 0.07949, 0.06045],    R@k:[0.04802, 0.13402, 0.19509, 0.27677],
(Training)map@k:[0.15042, 0.22485, 0.22736, 0.217], ndcg@k:[0.15042, 0.15024, 0.16505, 0.18964], elapse:0.543 min
(Test)  P@k:[0.23957, 0.15924, 0.12353, 0.09226],    R@k:[0.0351, 0.10221, 0.14645, 0.20534], 
(Test)map@k:[0.23957, 0.31215, 0.30276, 0.27688], ndcg@k:[0.23957, 0.19451, 0.18577, 0.19138], elapse:0.305 min
[ Epoch 14 ]
(Training)  P@k:[0.15517, 0.10217, 0.08009, 0.06128],    R@k:[0.04914, 0.13702, 0.19953, 0.28389], 
(Training)map@k:[0.15517, 0.23054, 0.2332, 0.22142], ndcg@k:[0.15517, 0.15386, 0.16867, 0.19418], elapse:0.544 min
(Test)  P@k:[0.24325, 0.15949, 0.12375, 0.09241],    R@k:[0.03591, 0.10231, 0.14727, 0.20622], 
(Test)map@k:[0.24325, 0.31464, 0.30366, 0.27798], ndcg@k:[0.24325, 0.19513, 0.1866, 0.19227], elapse:0.304 min
[ Epoch 15 ]
(Training)  P@k:[0.15715, 0.10321, 0.0813, 0.0623],    R@k:[0.05121, 0.13837, 0.20209, 0.28823], 
(Training)map@k:[0.15715, 0.23245, 0.23494, 0.22356], ndcg@k:[0.15715, 0.15581, 0.1711, 0.19719], elapse:0.544 min
(Test)  P@k:[0.24178, 0.16122, 0.12569, 0.09322],    R@k:[0.0355, 0.10296, 0.14868, 0.20674], 
(Test)map@k:[0.24178, 0.31552, 0.3045, 0.27955], ndcg@k:[0.24178, 0.19675, 0.1885, 0.19334], elapse:0.304 min
[ Epoch 16 ]
(Training)  P@k:[0.15928, 0.10616, 0.08352, 0.06373],    R@k:[0.0514, 0.1421, 0.20528, 0.29431], 
(Training)map@k:[0.15928, 0.23666, 0.239, 0.22684], ndcg@k:[0.15928, 0.15974, 0.1748, 0.20134], elapse:0.544 min
(Test)  P@k:[0.24563, 0.16254, 0.12522, 0.09313],    R@k:[0.03653, 0.1035, 0.14778, 0.2062], 
(Test)map@k:[0.24563, 0.31779, 0.30678, 0.28171], ndcg@k:[0.24563, 0.19846, 0.18883, 0.19397], elapse:0.305 min
[ Epoch 17 ]
(Training)  P@k:[0.15873, 0.10877, 0.08471, 0.06467],    R@k:[0.05087, 0.14612, 0.21082, 0.29801], 
(Training)map@k:[0.15873, 0.24014, 0.24154, 0.22919], ndcg@k:[0.15873, 0.16254, 0.17747, 0.20379], elapse:0.545 min
(Test)  P@k:[0.24692, 0.16247, 0.12602, 0.09349],    R@k:[0.03699, 0.10354, 0.14928, 0.20798], 
(Test)map@k:[0.24692, 0.31923, 0.30737, 0.28249], ndcg@k:[0.24692, 0.19881, 0.18998, 0.19503], elapse:0.305 min
[ Epoch 18 ]
(Training)  P@k:[0.16624, 0.10823, 0.08592, 0.06566],    R@k:[0.05351, 0.14688, 0.21425, 0.30486], 
(Training)map@k:[0.16624, 0.24358, 0.24539, 0.23274], ndcg@k:[0.16624, 0.16413, 0.18063, 0.20793], elapse:0.542 min
(Test)  P@k:[0.24472, 0.16164, 0.12533, 0.09323],    R@k:[0.03647, 0.10424, 0.14867, 0.20701], 
(Test)map@k:[0.24472, 0.31805, 0.30668, 0.28151], ndcg@k:[0.24472, 0.19797, 0.18904, 0.19433], elapse:0.305 min
[ Epoch 19 ]
(Training)  P@k:[0.16775, 0.11106, 0.0872, 0.06666],    R@k:[0.05382, 0.1481, 0.2157, 0.30694], 
(Training)map@k:[0.16775, 0.24677, 0.24808, 0.23464], ndcg@k:[0.16775, 0.1668, 0.18274, 0.2101], elapse:0.545 min
(Test)  P@k:[0.24508, 0.16199, 0.12563, 0.09259],    R@k:[0.03633, 0.10289, 0.14914, 0.20566], 
(Test)map@k:[0.24508, 0.31767, 0.30654, 0.2814], ndcg@k:[0.24508, 0.19786, 0.18917, 0.19346], elapse:0.308 min
[ Epoch 20 ]
(Training)  P@k:[0.16704, 0.11233, 0.08892, 0.06812],    R@k:[0.053, 0.15082, 0.22171, 0.31606],
(Training)map@k:[0.16704, 0.24917, 0.24985, 0.23676], ndcg@k:[0.16704, 0.16842, 0.18571, 0.21406], elapse:0.543 min
(Test)  P@k:[0.24628, 0.16313, 0.12636, 0.09309],    R@k:[0.03655, 0.10306, 0.14858, 0.20607], 
(Test)map@k:[0.24628, 0.31762, 0.30714, 0.28252], ndcg@k:[0.24628, 0.19915, 0.18996, 0.19426], elapse:0.305 min
[ Epoch 21 ]
(Training)  P@k:[0.18848, 0.12549, 0.0986, 0.07574],    R@k:[0.06187, 0.16858, 0.24688, 0.35069], 
(Training)map@k:[0.18848, 0.27292, 0.27278, 0.25692], ndcg@k:[0.18848, 0.18923, 0.2076, 0.23866], elapse:0.544 min
(Test)  P@k:[0.24894, 0.16486, 0.12677, 0.09367],    R@k:[0.03713, 0.10432, 0.14954, 0.2073],
(Test)map@k:[0.24894, 0.32087, 0.31005, 0.28441], ndcg@k:[0.24894, 0.20124, 0.19133, 0.19567], elapse:0.306 min
[ Epoch 22 ]
(Training)  P@k:[0.19046, 0.12866, 0.10127, 0.07741],    R@k:[0.06173, 0.17496, 0.25484, 0.36042], 
(Training)map@k:[0.19046, 0.27831, 0.27802, 0.26112], ndcg@k:[0.19046, 0.1943, 0.2132, 0.24478], elapse:0.544 min
(Test)  P@k:[0.24729, 0.16502, 0.12702, 0.09306],    R@k:[0.03706, 0.10468, 0.14961, 0.20543], 
(Test)map@k:[0.24729, 0.32079, 0.30929, 0.28426], ndcg@k:[0.24729, 0.20108, 0.19119, 0.19466], elapse:0.305 min
[ Epoch 23 ]
(Training)  P@k:[0.19362, 0.12969, 0.10284, 0.07788],    R@k:[0.06284, 0.17642, 0.25946, 0.3629], 
(Training)map@k:[0.19362, 0.28257, 0.28145, 0.26428], ndcg@k:[0.19362, 0.19638, 0.21647, 0.24735], elapse:0.545 min
(Test)  P@k:[0.24738, 0.16479, 0.12613, 0.09292],    R@k:[0.03701, 0.10432, 0.14939, 0.20525], 
(Test)map@k:[0.24738, 0.32024, 0.309, 0.28365], ndcg@k:[0.24738, 0.20074, 0.19053, 0.19437], elapse:0.305 min
[ Epoch 24 ]
(Training)  P@k:[0.1971, 0.13176, 0.10439, 0.07892],    R@k:[0.06356, 0.17953, 0.26352, 0.36897],
(Training)map@k:[0.1971, 0.28701, 0.28486, 0.26757], ndcg@k:[0.1971, 0.19964, 0.22004, 0.25133], elapse:0.545 min
(Test)  P@k:[0.2517, 0.16447, 0.12625, 0.09234],    R@k:[0.03746, 0.10417, 0.14906, 0.20408], 
(Test)map@k:[0.2517, 0.32071, 0.3106, 0.28448], ndcg@k:[0.2517, 0.20098, 0.19076, 0.19397], elapse:0.305 min
[ Epoch 25 ]
(Training)  P@k:[0.20597, 0.13569, 0.10704, 0.08005],    R@k:[0.06563, 0.18433, 0.26871, 0.37124], 
(Training)map@k:[0.20597, 0.29363, 0.29127, 0.27336], ndcg@k:[0.20597, 0.2052, 0.22523, 0.25542], elapse:0.544 min
(Test)  P@k:[0.25005, 0.16403, 0.12626, 0.09219],    R@k:[0.03718, 0.10414, 0.14894, 0.20422], 
(Test)map@k:[0.25005, 0.321, 0.30938, 0.28457], ndcg@k:[0.25005, 0.20073, 0.19068, 0.19383], elapse:0.305 min
[ Epoch 26 ]
(Training)  P@k:[0.20937, 0.13713, 0.10831, 0.08099],    R@k:[0.0674, 0.18636, 0.27492, 0.37729], 
(Training)map@k:[0.20937, 0.29787, 0.29598, 0.27696], ndcg@k:[0.20937, 0.20847, 0.22966, 0.26002], elapse:0.545 min
(Test)  P@k:[0.24821, 0.16412, 0.12557, 0.09189],    R@k:[0.03733, 0.10433, 0.14832, 0.20299], 
(Test)map@k:[0.24821, 0.31968, 0.30846, 0.28385], ndcg@k:[0.24821, 0.20044, 0.1899, 0.19315], elapse:0.306 min
[ Epoch 27 ]
(Training)  P@k:[0.21649, 0.13978, 0.10987, 0.08217],    R@k:[0.06937, 0.19024, 0.27725, 0.38366], 
(Training)map@k:[0.21649, 0.30323, 0.30011, 0.28064], ndcg@k:[0.21649, 0.2127, 0.23318, 0.26461], elapse:0.545 min
(Test)  P@k:[0.25078, 0.16429, 0.1256, 0.09189],    R@k:[0.03742, 0.10411, 0.14822, 0.20297], 
(Test)map@k:[0.25078, 0.32106, 0.31049, 0.28458], ndcg@k:[0.25078, 0.20107, 0.19034, 0.1935], elapse:0.306 min
[ Epoch 28 ]
(Training)  P@k:[0.21973, 0.14251, 0.11155, 0.08363],    R@k:[0.07004, 0.1923, 0.28057, 0.38814], 
(Training)map@k:[0.21973, 0.30772, 0.30418, 0.28325], ndcg@k:[0.21973, 0.21643, 0.23689, 0.26873], elapse:0.545 min
(Test)  P@k:[0.24729, 0.16385, 0.12568, 0.09186],    R@k:[0.03687, 0.10358, 0.14805, 0.20356], 
(Test)map@k:[0.24729, 0.31943, 0.30856, 0.28349], ndcg@k:[0.24729, 0.19992, 0.1897, 0.19306], elapse:0.304 min
[ Epoch 29 ]
(Training)  P@k:[0.22147, 0.14523, 0.1137, 0.08421],    R@k:[0.0714, 0.19744, 0.28571, 0.39185],
(Training)map@k:[0.22147, 0.31056, 0.30659, 0.28651], ndcg@k:[0.22147, 0.22009, 0.24058, 0.27159], elapse:0.544 min
(Test)  P@k:[0.25124, 0.16322, 0.12497, 0.09115],    R@k:[0.03717, 0.10316, 0.14719, 0.20187], 
(Test)map@k:[0.25124, 0.31992, 0.30941, 0.28371], ndcg@k:[0.25124, 0.20004, 0.18942, 0.19237], elapse:0.305 min
[ Epoch 30 ]
(Training)  P@k:[0.2248, 0.14825, 0.11511, 0.08509],    R@k:[0.07244, 0.20256, 0.2911, 0.39398], 
(Training)map@k:[0.2248, 0.31676, 0.31269, 0.29103], ndcg@k:[0.2248, 0.22517, 0.24515, 0.2754], elapse:0.546 min
(Test)  P@k:[0.24986, 0.16302, 0.12543, 0.09144],    R@k:[0.03745, 0.1034, 0.14771, 0.20235], 
(Test)map@k:[0.24986, 0.31957, 0.30852, 0.28434], ndcg@k:[0.24986, 0.19999, 0.18973, 0.19271], elapse:0.305 min
[I 2024-07-26 18:47:57,124] Trial 0 finished with value: 0.20124 and parameters: {}. Best is trial 0 with value: 0.20124.


Look for the best test recall and test ndcg in all of the epochs above?

**Comment by WangXFng** [comment]
Sorry for the confusion. I thought if it outputs all results, it would be more convenient to see how the model converges. 
I have revised the code and made it conclude the best result. 
Could you try the latest version of the code?

**Comment by Pursuerwener** [comment]
Thank you very much for your help
